### ISSUE TITLE
Nothing happens : help in config

### ISSUE THREAD

**Issue by jokerigno** [mathisdt/nextcloud-news-filter#1] opened 2023-04-08 16:14 UTC
Hi,

I followed the instruction to enable the filtering.

I run nextcloudpi in a lxc container in my mini pc running proxmox.

Using this guide (https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html)

I added the second row in my cron file
```

*/5  *  *  *  * php -f /var/www/nextcloud/cron.php 
*/5  *  *  *  * /usr/bin/php -f /var/www/nextcloud/cron.php ; ( /home/nextcloud-news-filter/main.py | grep -E '(filter|marking as read)' >>/home/nextcloud-news-filter/nextcloud-news-filter.log )

```

(config.ini and main.py are in my home folder
![image](https://user-images.githubusercontent.com/23552762/230731566-275f1363-db93-4823-96e0-c406af95f886.png)
)

I waited almost 24 hours but I checked and nothing happens.

This is my config.ini

```
[login]
address = https://cloud.xxxxxx.it

username = xxxx
password = xxxx

# The names of the following sections are not specified, use as description of the filter.
# optional parameter feedId -> apply only in this feed
# optional parameter titleRegex -> apply to item titles
# optional parameter bodyRegex -> apply to item bodies
# optional parameter hoursAge -> apply if item's "pubDate" is older than this

[example 1: filter in feed BLAH]
feedId = 23
titleRegex = unwanted.*juventus

[example 2: filter ads in all feeds]
bodyRegex = (advertisement|paid content)

[example 3: older than 72 hours]
hoursAge = 72
```

Does it looks right?

An important info: my username is protected by 2 factor auth (so I put a numeric code after login). Maybe is this the reason why it does not work?

Unfortunately the log file is created but is empty.

**Comment by mathisdt** [comment] 2023-04-10 08:21
Hi,
here are some thoughts regarding the described setup:

1. ```
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php 
*/5  *  *  *  * /usr/bin/php -f /var/www/nextcloud/cron.php ; ( /home/nextcloud-news-filter/main.py | grep -E '(filter|marking as read)' >>/home/nextcloud-news-filter/nextcloud-news-filter.log )
```This

**Comment by mathisdt** [comment] 2023-04-10 08:36
Hi,
here are some thoughts regarding the described setup:

1. In your crontab, the second line looks right, but the first line is unnecessary - or maybe even a problem because it does the same thing (call Nextcloud's cron hook) at the same time (`*/5` = every five minutes).  
```
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php 
*/5  *  *  *  * /usr/bin/php -f /var/www/nextcloud/cron.php ; ( /home/nextcloud-news-filter/main.py | grep -E '(filter|marking as read)' >>/home/nextcloud-news-filter/nextcloud-news-filter.log )
```
2. The filters you defined look a lot like the examples I provided initially. I don't know what you want to achieve, but I'll outline shortly what I think would help you. I suspect you don't want to see anything related to Juventus, so I propose these two filters instead of the three you have at the moment:  
```
[filter out anything with juventus in title]
titleRegex = juventus

[filter out anything with juventus in body]
bodyRegex = juventus
```
3. If you want so see more information in the log file, you could remove the grep statement so that your crontab entry looks like this:  
```
*/5  *  *  *  * /usr/bin/php -f /var/www/nextcloud/cron.php ; ( /home/nextcloud-news-filter/main.py >>/home/nextcloud-news-filter/nextcloud-news-filter.log )
```  
But be cautious, his way the log could grow fastly.

**Comment by mathisdt** [comment] 2023-04-12 19:20
I think the KeyError is caused by the 2FA you mentioned. In Nextcloud's manual, the standard way for this situation is to create an "app password" or a "device password". Please see [here](https://docs.nextcloud.com/server/latest/user_manual/en/session_management.html#managing-devices) for more information. As far as I understand it, you generate this new password and then can use that for API accesses like for the news filter.

**Comment by mathisdt** [comment] 2023-04-12 19:27
As to why the error is not displayed in the log file: apparently I forgot to redirect the error channel to the standard output channel (`2>&1`) before the latter is redirected to the file (`>>/path/to/nextcloud-news-filter.log`). I added that to the [readme](https://github.com/mathisdt/nextcloud-news-filter/blob/master/README.md#when-and-how-to-run), you also should insert the redirect `2>&1` in your crontab to also log errors.

**Comment by jokerigno** [comment] 2023-04-16 15:53
OK the specific "app password" did the trick,

Unfortunately the cron part is stil not working (don't know why but nothing appears in the log).

Below new crontab file

`*/5  *  *  *  * php -f /var/www/nextcloud/cron.php
*/1  *  *  *  * /usr/bin/php -f /var/www/nextcloud/cron.php ; ( /home/nextcloud-news-filter/main.py | grep -E '(filter|marking as read)' 2>&1 >>/home/nextcloud-news-filter/nextcloud-news-filter.log )`

another thing that I don't understand is how to add many words in "titleRegex". If i do something like 

`titleRegex = juventus, calcio`

I see this error

```
root@nextcloudpi:~# /home/nextcloud-news-filter/main.py
2023-04-16 17:48:49,807 - root - DEBUG - starting run
Traceback (most recent call last):
  File "/home/nextcloud-news-filter/main.py", line 25, in <module>
    config.read(configfile)
  File "/usr/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.9/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/home/nextcloud-news-filter/config.ini' [line 18]: option 'titleregex' in section 'example 1: filter in feed TorinoToday' already exists

```
any suggestion for a noob like me?

Thanks in advance

**Comment by mathisdt** [comment] 2023-04-16 17:17
If you absolutely want to keep the original line `*/5  *  *  *  * php -f /var/www/nextcloud/cron.php` then you could make the second line look like this (without the first part which is a duplicate of the first line):
```
*/1  *  *  *  * /home/nextcloud-news-filter/main.py | grep -E '(filter|marking as read)' 2>&1 >>/home/nextcloud-news-filter/nextcloud-news-filter.log
```

And if you want to filter out multiple terms, you can (1) build a regular expression which does that ([here's some help](https://docs.python.org/3.9/library/re.html#re.sub) on that) or you can (2) use different filters.

Example for 1:
```
titleRegex = (juventus|calcio)
```

Example for 2:
```
[filter out juventus]
titleRegex = juventus

[filter out calcio]
titleRegex = calcio
```

**Comment by mathisdt** [comment] 2024-02-23 11:55
I suppose that it works now - if not, feel free to reopen the issue!

**Closed by mathisdt** 2024-02-23 11:55 UTC
